apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
    #  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector: 
    app: monitoring
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000
